apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapMame}}
  labels:
    {{- include "homework2.labels" . | nindent 4 }}
data:
  DATABASE_USER: "myuser"
  DATABASE_HOST: "postgres"
  DATABASE_NAME: "myapp"
